const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.skymen_better_input_manager,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Camera3D,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Internationalization,
		C3.Plugins.Avix_PokiSDK_ForC3,
		C3.Plugins.skymen_mask,
		C3.Plugins.BinaryData,
		C3.Plugins.skymen_limit_fps,
		C3.Plugins.Colyseus_SDK,
		C3.Plugins.skymen_GlobalRuntime,
		C3.Plugins.Shape3D,
		C3.Plugins.Date,
		C3.Plugins.TiledBg,
		C3.Plugins.Mikal_3DObject,
		C3.Plugins.Text,
		C3.Behaviors.skymen_mesh_rotate,
		C3.Plugins.NinePatch,
		C3.Behaviors.Sin,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.skymen_bounding_box,
		C3.Behaviors.skymen_scrollview,
		C3.Behaviors.Anchor,
		C3.Behaviors.Fade,
		C3.Plugins.skymen_Shell,
		C3.Plugins.Particles,
		C3.Behaviors.YellowAfterlife_FastRadialProgressBar,
		C3.Behaviors.EightDir,
		C3.Behaviors.LOS,
		C3.Behaviors.Follow,
		C3.Behaviors.mikal_rotate_shape,
		C3.Behaviors.solid,
		C3.ScriptsInEvents.Utils_Event1_Act1,
		C3.ScriptsInEvents.Utils_Event2_Act1,
		C3.ScriptsInEvents.Utils_Event3_Act1,
		C3.ScriptsInEvents.Utils_Event4_Act1,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.ScriptsInEvents.Utils_Event6_Act1,
		C3.ScriptsInEvents.Utils_Event7_Act1,
		C3.ScriptsInEvents.Utils_Event9_Act1,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.System.Exps.log10,
		C3.ScriptsInEvents.Utils_Event13_Act1,
		C3.ScriptsInEvents.Utils_Event14_Act1,
		C3.ScriptsInEvents.Utils_Event15_Act1,
		C3.ScriptsInEvents.Utils_Event23_Act1,
		C3.ScriptsInEvents.Utils_Event24_Act1,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.Else,
		C3.ScriptsInEvents.Utils_Event43_Act1,
		C3.ScriptsInEvents.Utils_Event44_Act1,
		C3.ScriptsInEvents.Utils_Event45_Act1,
		C3.ScriptsInEvents.Utils_Event46_Act1,
		C3.Plugins.Internationalization.Exps.Lookup,
		C3.Plugins.System.Cnds.Compare,
		C3.ScriptsInEvents.Utils_Event56_Act1,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.skymen_better_input_manager.Cnds.OnAnyDown,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStart,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStop,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestCommercialBreak,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnCommercialBreakComplete,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestRewardedBreak,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnRewardedBreakComplete,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Shape3D.Exps.TotalZElevation,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Mikal_3DObject.Cnds.OnCreated,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mikal_3DObject.Acts.SetAnimationSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Angle,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Camera3D.Acts.SetFieldOfView,
		C3.Behaviors.skymen_scrollview.Acts.SetProgressY,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.NinePatch.Cnds.PickTopBottom,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.ScriptsInEvents.E_uicomponents_Event78_Act1,
		C3.Behaviors.skymen_scrollview.Exps.VectorY,
		C3.Behaviors.skymen_scrollview.Exps.ScrollProgressY,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Behaviors.skymen_scrollview.Acts.SetVectorY,
		C3.Plugins.Mouse.Exps.WheelDeltaY,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.Touch.Exps.TouchIndex,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.RemoveLayer,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Mouse.Acts.ReleasePointerLock,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.NinePatch.Exps.BBoxMidX,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.skymen_mask.Cnds.PickTopBottom,
		C3.Behaviors.skymen_scrollview.Acts.SetInstance,
		C3.Plugins.skymen_mask.Acts.MoveToTop,
		C3.Plugins.NinePatch.Acts.MoveToTop,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.stringsub,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Json.Exps.UID,
		C3.ScriptsInEvents.E_dialogs_Event34_Act1,
		C3.ScriptsInEvents.E_dialogs_Event35_Act1,
		C3.Plugins.Audio.Acts.Preload,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.PlayAtObjectByName,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Shape3D.Cnds.OnDestroyed,
		C3.Plugins.Shape3D.Exps.UID,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.AddFilterEffect,
		C3.Plugins.Audio.Acts.RemoveEffects,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.AdvancedRandom.Acts.ShufflePermutationTable,
		C3.Plugins.Json.Acts.SetPath,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.AdvancedRandom.Acts.SetOctaves,
		C3.ScriptsInEvents.E_game_Event3_Act1,
		C3.Plugins.skymen_Shell.Exps.Count,
		C3.Plugins.Mikal_3DObject.Cnds.OnLoaded,
		C3.Plugins.PlatformInfo.Exps.Renderer,
		C3.Plugins.Mikal_3DObject.Acts.SetStaticGeometry,
		C3.Plugins.Mikal_3DObject.Exps.LayerNumber,
		C3.Plugins.Mikal_3DObject.Exps.X,
		C3.Plugins.Mikal_3DObject.Exps.Y,
		C3.Plugins.Shape3D.Acts.SetBoolInstanceVar,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Mikal_3DObject.Exps.ZAngle,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Mikal_3DObject.Exps.ZElevation,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Plugins.Mikal_3DObject.Exps.ZScale,
		C3.Plugins.Mikal_3DObject.Exps.Scale,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Plugins.Mikal_3DObject.Exps.XScale,
		C3.Plugins.Mikal_3DObject.Acts.AddChild,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Mikal_3DObject.Exps.YScale,
		C3.Plugins.Sprite.Cnds.CompareZElevation,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.skymen_better_input_manager.Cnds.OnDown,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Behaviors.Timer.Acts.PauseResumeAllTimers,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.LastAdRewardSuccess,
		C3.Plugins.Shape3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Acts.AddChild,
		C3.Plugins.Mikal_3DObject.Acts.SetZElevation,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Mikal_3DObject.Acts.SetRotationOrdered,
		C3.Plugins.Mikal_3DObject.Exps.XAngle,
		C3.Plugins.Mikal_3DObject.Exps.YAngle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Shape3D.Exps.LayerNumber,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.ScriptsInEvents.E_game_Event44_Act2,
		C3.Plugins.Sprite.Exps.dt,
		C3.Plugins.Shape3D.Exps.Count,
		C3.ScriptsInEvents.E_game_Event45_Act1,
		C3.ScriptsInEvents.E_game_Event47_Act2,
		C3.ScriptsInEvents.E_game_Event48_Act1,
		C3.Plugins.Json.Acts.SetObject,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.ScriptsInEvents.E_game_Event49_Act1,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.Shape3D.Acts.SetEffectParam,
		C3.Plugins.TiledBg.Acts.SetEffectParam,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Shape3D.Exps.ColorValue,
		C3.Plugins.Shape3D.Acts.SetDefaultColor,
		C3.Plugins.Shape3D.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.TiledBg.Acts.SetZElevation,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Behaviors.EightDir.Exps.MovingAngle,
		C3.Behaviors.EightDir.Exps.Speed,
		C3.Plugins.TiledBg.Exps.ImageScaleX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageScaleY,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.TiledBg.Acts.SetMeshSize,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.ScriptsInEvents.E_game_Event71,
		C3.ScriptsInEvents.E_game_Event73,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.ScriptsInEvents.E_game_Event80,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.ScriptsInEvents.E_game_Event84_Act1,
		C3.Plugins.Shape3D.Cnds.PickByUID,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Cnds.PickChildren,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Shape3D.Cnds.PickChildren,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.Shape3D.Acts.SetHeight,
		C3.Plugins.Shape3D.Exps.Height,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Shape3D.Acts.MoveAtAngle,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.Shape3D.Cnds.PickParent,
		C3.Plugins.Mouse.Cnds.HasPointerLock,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Shape3D.Acts.SetVisible,
		C3.ScriptsInEvents.E_game_Event132_Act1,
		C3.ScriptsInEvents.E_game_Event134_Act1,
		C3.ScriptsInEvents.E_game_Event136_Act1,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Shape3D.Acts.SetX,
		C3.Plugins.Shape3D.Acts.SetY,
		C3.ScriptsInEvents.E_game_Event145_Act1,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Exps.LayerName,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Exps.LayerNumber,
		C3.Plugins.Text.Exps.BBoxRight,
		C3.Plugins.Text.Exps.BBoxMidY,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.CommercialBreakPossible,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Exps.ZElevation,
		C3.Plugins.Mikal_3DObject.Acts.PlayAnimation,
		C3.Plugins.Text.Exps.Angle,
		C3.Plugins.Text.Acts.SetAngle,
		C3.Behaviors.skymen_mesh_rotate.Acts.SetFromVectors,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Sprite.Acts.SetMeshSize,
		C3.ScriptsInEvents.E_game_Event182_Act1,
		C3.Plugins.skymen_better_input_manager.Acts.SimulateDownInput,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.skymen_better_input_manager.Acts.SetDownInput,
		C3.Plugins.skymen_better_input_manager.Acts.SetUpInput,
		C3.Plugins.skymen_better_input_manager.Acts.SetAxisValue,
		C3.Plugins.skymen_better_input_manager.Cnds.IsDown,
		C3.Plugins.skymen_better_input_manager.Acts.SetJoystickValue,
		C3.Plugins.Mouse.Acts.RequestPointerLock,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Mouse.Exps.MovementY,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Touch.Exps.XForID,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.YForID,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.PlatformInfo.Exps.CanvasCssHeight,
		C3.Plugins.PlatformInfo.Exps.CanvasCssWidth,
		C3.Plugins.Touch.Exps.AngleForID,
		C3.Plugins.Touch.Exps.SpeedForID,
		C3.ScriptsInEvents.E_player_Event2_Act4,
		C3.Plugins.System.Exps.wallclocktime,
		C3.Plugins.skymen_better_input_manager.Cnds.OnUp,
		C3.Plugins.System.Exps.time,
		C3.Plugins.System.Exps.anglediff,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Plugins.System.Exps.max,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.EightDir.Exps.VectorX,
		C3.Behaviors.EightDir.Exps.VectorY,
		C3.Plugins.skymen_better_input_manager.Cnds.IsJoystickOutsideDeadzone,
		C3.Plugins.skymen_better_input_manager.Exps.GetJoystickAngle,
		C3.Plugins.skymen_better_input_manager.Exps.GetJoystickX,
		C3.Plugins.skymen_better_input_manager.Exps.GetJoystickY,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.ScriptsInEvents.E_player_Event101_Act1,
		C3.Plugins.Audio.Acts.PlayAtPosition,
		C3.Plugins.Sprite.Acts.InstanceSignal,
		C3.Behaviors.LOS.Exps.HitUID,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Behaviors.LOS.Exps.NormalAngle,
		C3.Plugins.Shape3D.Cnds.CompareShape,
		C3.Behaviors.LOS.Exps.HitX,
		C3.Behaviors.LOS.Exps.HitY,
		C3.ScriptsInEvents.E_player_Event174_Act1,
		C3.Plugins.Shape3D.Cnds.CompareZHeight,
		C3.Plugins.Camera3D.Exps.LookVectorZ,
		C3.Plugins.Camera3D.Exps.LookVectorX,
		C3.Plugins.Camera3D.Exps.LookVectorY,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Behaviors.Follow.Acts.ClearHistory,
		C3.Behaviors.Follow.Acts.FollowSelf,
		C3.Plugins.Camera3D.Exps.FieldOfView,
		C3.Behaviors.Sin.Exps.Value,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.mikal_rotate_shape.Acts.SetCenterOffset,
		C3.Behaviors.mikal_rotate_shape.Acts.SetRotationAngles,
		C3.ScriptsInEvents.E_player_Event278_Act1,
		C3.Behaviors.Follow.Cnds.HasFollowData,
		C3.Behaviors.Follow.Cnds.CompareHistoryRate,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Browser.Acts.SetWarnOnClose,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Internationalization.Acts.LoadFromJSON,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Cnds.LayerNameExists,
		C3.Plugins.System.Acts.SetLayerTransparent,
		C3.Plugins.skymen_limit_fps.Acts.SetMaxFPS,
		C3.Plugins.System.Acts.SetFramerateMode,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Sprite.Cnds.OnInstanceSignal,
		C3.Plugins.Json.Acts.AddTo,
		C3.Plugins.Mikal_3DObject.Exps.UID,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Camera3D.Exps.ForwardX,
		C3.Plugins.Camera3D.Exps.ForwardY,
		C3.Plugins.Audio.Acts.SetListenerObject,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Plugins.Audio.Acts.SetListenerOrientation,
		C3.Plugins.Camera3D.Exps.ForwardZ,
		C3.Plugins.Camera3D.Exps.UpX,
		C3.Plugins.Camera3D.Exps.UpY,
		C3.Plugins.Camera3D.Exps.UpZ,
		C3.Plugins.Audio.Acts.SetListenerZ,
		C3.Plugins.AdvancedRandom.Exps.Classic2d,
		C3.ScriptsInEvents.E_camera_Event23_Act1,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxMidY,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.NinePatch.Exps.LayerNumber,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.ScriptsInEvents.E_levelprogress_Event15_Act1,
		C3.Plugins.Shape3D.Acts.SetFaceVisible,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Shape3D.Exps.IID,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Json.Acts.InstanceSignal,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.ScriptsInEvents.E_savesystem_Event15_Act5,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Mouse.Cnds.OnPointerUnlocked,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.ScriptsInEvents.E_debug_Event4_Act1,
		C3.ScriptsInEvents.E_debug_Event5_Act1,
		C3.Plugins.Mikal_3DObject.Acts.SetZElevation0,
		C3.Plugins.System.Exps.objectcount,
		C3.Plugins.PlatformInfo.Exps.FramesPerSecond,
		C3.Plugins.PlatformInfo.Exps.TicksPerSecond,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.System.Exps.cpuutilisation,
		C3.Plugins.System.Exps.gpuutilisation,
		C3.Plugins.Colyseus_SDK.Acts.SetEndpoint,
		C3.Plugins.Colyseus_SDK.Acts.JoinOrCreateRoom,
		C3.Plugins.Colyseus_SDK.Exps.JSON,
		C3.ScriptsInEvents.E_remoteplayer_Event12_Act1,
		C3.ScriptsInEvents.E_remoteplayer_Event13_Act1,
		C3.Plugins.System.Cnds.OnSuspend,
		C3.ScriptsInEvents.E_remoteplayer_Event16_Act1,
		C3.Plugins.System.Cnds.OnResume,
		C3.ScriptsInEvents.E_remoteplayer_Event17_Act1,
		C3.Plugins.Colyseus_SDK.Acts.RoomLeave,
		C3.Plugins.Colyseus_SDK.Cnds.OnLeaveRoom,
		C3.Plugins.Colyseus_SDK.Cnds.OnJoinRoom,
		C3.Plugins.Mikal_3DObject.Acts.MoveToLayer,
		C3.ScriptsInEvents.E_remoteplayer_Event27_Act1,
		C3.ScriptsInEvents.E_remoteplayer_Event28_Act1,
		C3.Plugins.Colyseus_SDK.Cnds.OnCollectionItemAdd,
		C3.Plugins.Colyseus_SDK.Exps.CurrentKey,
		C3.Plugins.Colyseus_SDK.Cnds.OnCollectionItemRemove,
		C3.Plugins.Colyseus_SDK.Acts.RoomSendJSON,
		C3.Plugins.Colyseus_SDK.Cnds.OnStateChange,
		C3.Plugins.Colyseus_SDK.Exps.State,
		C3.Plugins.Colyseus_SDK.Exps.SessionId,
		C3.ScriptsInEvents.E_remoteplayer_Event37_Act4,
		C3.Plugins.Mikal_3DObject.Cnds.IsLoaded,
		C3.Plugins.Mikal_3DObject.Acts.SetInstanceVar,
		C3.Plugins.Mikal_3DObject.Cnds.CompareInstanceVar,
		C3.Plugins.Mikal_3DObject.Acts.InstanceSignal,
		C3.Plugins.Shape3D.Cnds.OnInstanceSignal,
		C3.ScriptsInEvents.E_remoteplayer_Event45_Act1,
		C3.Plugins.Mikal_3DObject.Acts.SetAnimationRate,
		C3.Plugins.Mikal_3DObject.Acts.SetPos,
		C3.Plugins.Mikal_3DObject.Acts.SetVisible,
		C3.Plugins.Mikal_3DObject.Acts.SetBoolInstanceVar,
		C3.ScriptsInEvents.E_remoteplayer_Event54_Act1,
		C3.Plugins.Shape3D.Acts.InstanceSignal,
		C3.Plugins.Mikal_3DObject.Cnds.OnInstanceSignal,
		C3.Plugins.Mikal_3DObject.Acts.SetAnimationBlend,
		C3.Plugins.Mikal_3DObject.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.IsClockwiseFrom,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Exps.FaceSize,
		C3.ScriptsInEvents.E_remoteplayer_Event114,
		C3.ScriptsInEvents.E_remoteplayer_Event116_Act1,
		C3.Plugins.Text.Acts.SetZElevation,
		C3.Plugins.Mikal_3DObject.Acts.SetZScale,
		C3.Plugins.Mikal_3DObject.Acts.SetYScale,
		C3.Plugins.Mikal_3DObject.Acts.SetXScale,
		C3.Plugins.Json.Acts.DeleteKey,
		C3.Plugins.Json.Exps.Path,
		C3.Plugins.Json.Acts.SubtractFrom,
		C3.Behaviors.YellowAfterlife_FastRadialProgressBar.Acts.SetValue,
		C3.Behaviors.YellowAfterlife_FastRadialProgressBar.Acts.SetMaxValue,
		C3.Plugins.Json.Acts.SetBoolean,
		C3.Plugins.Mikal_3DObject.Acts.SetDefaultColor,
		C3.Plugins.Mikal_3DObject.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Mikal_3DObject.Acts.Destroy,
		C3.Plugins.Camera3D.Exps.LayerToLayerX,
		C3.Plugins.Camera3D.Exps.LayerToLayerY,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Mikal_3DObject.Cnds.PickChildren,
		C3.Plugins.Mikal_3DObject.Acts.SetScale,
		C3.Plugins.Mikal_3DObject.Cnds.PickDistance,
		C3.Plugins.Mikal_3DObject.Acts.SetX,
		C3.Plugins.System.Cnds.PickAll,
		C3.ScriptsInEvents.E_skin_Event69,
		C3.Plugins.Mikal_3DObject.Acts.SetGPUSkinning,
		C3.Plugins.Mikal_3DObject.Acts.EnableNode,
		C3.Plugins.Json.Cnds.IsBooleanSet,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Plugins.skymen_Shell.Acts.SetSource,
		C3.Plugins.skymen_Shell.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Colyseus_SDK.Cnds.OnMessage,
		C3.Plugins.Colyseus_SDK.Exps.MessageValue,
		C3.Plugins.Colyseus_SDK.Acts.RoomSend,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyLoadingFinished,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Text.Cnds.CompareText
	];
};
self.C3_JsPropNameTable = [
	{Inputs: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{camera: 0},
	{Audio: 0},
	{AJAX: 0},
	{save: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{AdvancedRandom: 0},
	{PlatformInfo: 0},
	{curLevel: 0},
	{curChapter: 0},
	{curChapterProgress: 0},
	{curChapterMaxProgress: 0},
	{nextLevel: 0},
	{curDisplayedChapter: 0},
	{previousLayout: 0},
	{curGameMode: 0},
	{Tween: 0},
	{Timer: 0},
	{globalManager: 0},
	{levelData: 0},
	{playlist: 0},
	{tempGhost: 0},
	{i18n: 0},
	{PokiSDK: 0},
	{ClippingMask: 0},
	{achievementData: 0},
	{BinaryData: 0},
	{LimitFPS: 0},
	{Colyseus: 0},
	{playerDataJSON: 0},
	{GlobalRuntime: 0},
	{isFront: 0},
	{doorCollider: 0},
	{names: 0},
	{hitUID: 0},
	{hitX: 0},
	{hitY: 0},
	{hitZ: 0},
	{lastCastHit: 0},
	{rayCastData: 0},
	{powerUpState: 0},
	{skinDataJSON: 0},
	{Date: 0},
	{skybox_cloudy: 0},
	{cloudPlane: 0},
	{skybox_gradient: 0},
	{skybox_deepBlue: 0},
	{skybox_greySky: 0},
	{skybox_frosty: 0},
	{deformPlane: 0},
	{"3DObjectPowerUp": 0},
	{MeshRotate: 0},
	{PowerUpWorldText: 0},
	{edgesTexture: 0},
	{blackFillTexture: 0},
	{concreteTexture: 0},
	{darkTarTexture: 0},
	{gridTexture: 0},
	{dirtyEdgesTexture: 0},
	{speedTexture: 0},
	{powerBoxSideTexture: 0},
	{powerBoxTopTexture: 0},
	{tarpTexture: 0},
	{TilesTexture: 0},
	{stripesTexture: 0},
	{crossPatternTexture: 0},
	{plankTexture: 0},
	{cardBoardBox: 0},
	{whiteRectangleTexture: 0},
	{ventShaftTileTexture: 0},
	{vent: 0},
	{ventShaftTileSquashedTexture: 0},
	{TilesTextureDark: 0},
	{verticalPanelTexture: 0},
	{containerSides: 0},
	{containerShortSide: 0},
	{zCorpTexture: 0},
	{attentionTexture: 0},
	{concreteTextureUnderside: 0},
	{arrowTexture: 0},
	{zzCorpLogoTexture: 0},
	{brightCornersTexture: 0},
	{pressurePlateTopTexture: 0},
	{grafittiTestTexture: 0},
	{brickTexture: 0},
	{yellowWhiteTexture: 0},
	{whiteTexture: 0},
	{ArrowDown: 0},
	{woodPlanksTexture: 0},
	{sandstoneBricksTexture: 0},
	{sandStoneTexture: 0},
	{graffitiPiece: 0},
	{glassTexture: 0},
	{doorTexture: 0},
	{solarPanelTexture: 0},
	{doorTextureMirrored: 0},
	{holdOnHL2: 0},
	{ArrowUp: 0},
	{iceTexture: 0},
	{snowTopTexture: 0},
	{snowTiles9p: 0},
	{Text_performance: 0},
	{sliderID: 0},
	{value: 0},
	{sliderBar: 0},
	{initialI18nID: 0},
	{Text_slider: 0},
	{Text_inputs: 0},
	{Text_button: 0},
	{oWidth: 0},
	{oHeight: 0},
	{id: 0},
	{buttonState: 0},
	{isEnabled: 0},
	{animationStrength: 0},
	{basicButton: 0},
	{whiteFillTexture: 0},
	{yAnchorType: 0},
	{xAnchorType: 0},
	{anchor: 0},
	{starNr: 0},
	{starState: 0},
	{targetTime: 0},
	{Sine: 0},
	{star: 0},
	{Text_bestTime: 0},
	{Text_Timer: 0},
	{crosshair: 0},
	{starCompletedFill: 0},
	{loadingBar: 0},
	{targetY: 0},
	{achievementBG: 0},
	{Text_achievement: 0},
	{dialogBg: 0},
	{levelID: 0},
	{levelSelectButton: 0},
	{levelSelectStarFill: 0},
	{levelSelectStarUI: 0},
	{Text_dialogHeader: 0},
	{Text_levelName: 0},
	{Text_levelSelectBestTime: 0},
	{DragDrop: 0},
	{sliderHandle: 0},
	{bounding_box: 0},
	{bbox: 0},
	{ScrollView: 0},
	{scrollView: 0},
	{Text_DevNames: 0},
	{Text_curLevelTimes: 0},
	{Text_curLevelDataHeader: 0},
	{logo: 0},
	{Anchor: 0},
	{loadingBarBg: 0},
	{achievementSymbol: 0},
	{touchStickInner: 0},
	{touchStickOuterCircle: 0},
	{icons: 0},
	{achievementUnlock: 0},
	{Text_achievementUnlock: 0},
	{Text_achievementUnlockCounter: 0},
	{Text_CreditText: 0},
	{screenMessageBG: 0},
	{text_screenMessage: 0},
	{levelSelectSecretBG: 0},
	{Text_rewardedDialogText: 0},
	{chapterProgress: 0},
	{chapterProgressHeaderBG: 0},
	{Text_ChapterProgressHeader: 0},
	{order: 0},
	{chapterProgressMarker: 0},
	{Text_ChapterName: 0},
	{chapterProgressBar: 0},
	{chapterProgressBarBG: 0},
	{cursor: 0},
	{targetUID: 0},
	{worldHudMarker: 0},
	{Text_inspectable: 0},
	{messageBg: 0},
	{lockPointerText: 0},
	{worldTargetDistanceText: 0},
	{loadingText: 0},
	{achievementProgressBar: 0},
	{achievementProgressBarBG: 0},
	{Text_achievementUnlockHeader: 0},
	{Text_achievementHeader: 0},
	{isOpen: 0},
	{emoteWheel: 0},
	{emoteIcon: 0},
	{targetAngle: 0},
	{emoteWheelArrow: 0},
	{emote: 0},
	{loadingRandomText: 0},
	{playerProfileBG: 0},
	{Text_playerName: 0},
	{Fade: 0},
	{musicPlayer: 0},
	{Text_SongArtistName: 0},
	{curLevelDataBG: 0},
	{coverBGMask: 0},
	{emptyEmoteIcon: 0},
	{hasMultiplayerIcon: 0},
	{playerProfilePicture: 0},
	{uiCorner: 0},
	{staticLocaText: 0},
	{TagPopup: 0},
	{forwardX: 0},
	{forwardY: 0},
	{forwardZ: 0},
	{RotationAngle: 0},
	{world_text: 0},
	{Text_leadsToHeader: 0},
	{leadsToBG: 0},
	{Text_LeadsToInfo: 0},
	{Text_photoMode: 0},
	{cameraInfoBg: 0},
	{focalBar: 0},
	{cameraFocusIcons: 0},
	{focusingSliderHead: 0},
	{photoModeRect: 0},
	{cameraShutterMask: 0},
	{levelEndParticles: 0},
	{powerUpIcon: 0},
	{type: 0},
	{powerUpBG: 0},
	{Text_remotePlayerName: 0},
	{belongsToUid: 0},
	{shouldBeVisible: 0},
	{remotePlayerHudParent: 0},
	{FastRadialProgressBar: 0},
	{powerUpProgress: 0},
	{skinStateIcon: 0},
	{skinviewUI: 0},
	{skinDescription: 0},
	{fadeStart: 0},
	{fullVisibleDistance: 0},
	{Text_UnlockHardTrials: 0},
	{Text_skinDescription: 0},
	{Text_skinName: 0},
	{Text_skinUnlocked: 0},
	{Text_coinChange: 0},
	{Text_playerData: 0},
	{text_coins: 0},
	{index: 0},
	{nameType: 0},
	{Text_changeName: 0},
	{groupName: 0},
	{uiGrouper: 0},
	{groundSpeed: 0},
	{groundFriction: 0},
	{maxGroundAccel: 0},
	{airSpeed: 0},
	{airFriction: 0},
	{maxAirAccel: 0},
	{stopSpeed: 0},
	{slopePushAngleThreshold: 0},
	{slopePushForce: 0},
	{jumpStrength: 0},
	{baseGravity: 0},
	{gravity: 0},
	{maxFallSpeed: 0},
	{zStep: 0},
	{standHeight: 0},
	{currentHeight: 0},
	{wallrunningSlideSpeedLimit: 0},
	{wallrunningStickyLength: 0},
	{momentum: 0},
	{vectorZ: 0},
	{zFloor: 0},
	{zCeiling: 0},
	{floorAngle: 0},
	{slideAngle: 0},
	{shouldBePushed: 0},
	{curGroundType: 0},
	{curGroundSoundType: 0},
	{isWallrunning: 0},
	{wallRunWallNormalAngle: 0},
	{lookAngle: 0},
	{lastWallUID: 0},
	{hasJumped: 0},
	{state: 0},
	{floorUID: 0},
	{wallRunWallSoundType: 0},
	{isSliding: 0},
	{wallJumpStrength: 0},
	{speedBeforeWallClimb: 0},
	{nbConsecutiveWallClimbs: 0},
	{curLerpRotX: 0},
	{curLerpRotY: 0},
	{tempWallJumpAngle: 0},
	{floorZStep: 0},
	{airZStep: 0},
	{airFallZStep: 0},
	{wallClimbZStep: 0},
	{slideStartTime: 0},
	{nbConsecutiveWallRun: 0},
	{maxWallInteractionFallSpeed: 0},
	{lastZ: 0},
	{glideTime: 0},
	{gravityModifier: 0},
	{lastAngle: 0},
	{lastDT: 0},
	{hasAirDashed: 0},
	{previousX: 0},
	{previousY: 0},
	{Movement: 0},
	{LOS: 0},
	{Follow: 0},
	{player: 0},
	{Rotate3D: 0},
	{playerShadow: 0},
	{GhostShape: 0},
	{cctvCamera: 0},
	{Cone: 0},
	{Pipe: 0},
	{cable: 0},
	{edgeTarp: 0},
	{cornerTarp: 0},
	{pole: 0},
	{snowman: 0},
	{shouldBeMarkedInHud: 0},
	{goToNext: 0},
	{override: 0},
	{travelingTo: 0},
	{endZone: 0},
	{doRandomSpawn: 0},
	{padding: 0},
	{startZone: 0},
	{groundType: 0},
	{groundSoundType: 0},
	{isWallrunable: 0},
	{isWallClimbable: 0},
	{solidCollisionShape: 0},
	{pressurePlateHelper: 0},
	{isDepressed: 0},
	{xOffset: 0},
	{yOffset: 0},
	{zOffset: 0},
	{tweenDuration: 0},
	{AngleOffset: 0},
	{Delay: 0},
	{pressurePlate1: 0},
	{soundName: 0},
	{volume: 0},
	{pickUpType: 0},
	{pickUpID: 0},
	{pickUpCrystal: 0},
	{speedFloor: 0},
	{pickUpAsset: 0},
	{distanceRandom: 0},
	{sizeRandom: 0},
	{test3dParticle: 0},
	{stripes: 0},
	{decal: 0},
	{grafittiTestDecal: 0},
	{VerticalFootstep: 0},
	{decal2: 0},
	{grafittiTestDecal2: 0},
	{decal3: 0},
	{concreteShape: 0},
	{tarpBox: 0},
	{metalGround: 0},
	{railing: 0},
	{powerBox: 0},
	{blackShape: 0},
	{TiledShape: 0},
	{plank: 0},
	{box: 0},
	{ventPipe: 0},
	{woodPlanksShape: 0},
	{verticalPanels: 0},
	{TiledShape2: 0},
	{pickUpTest: 0},
	{whiteYellowWall: 0},
	{simpleWhiteWall: 0},
	{brokenConcretePillar: 0},
	{manhole: 0},
	{mural: 0},
	{mural2: 0},
	{neverRainSticker: 0},
	{wireMesh: 0},
	{footstepDecal: 0},
	{footstepDecal2: 0},
	{footstepDecal3: 0},
	{TiledShape3: 0},
	{sandStoneBrickShape: 0},
	{sandStoneShape: 0},
	{canBeInteracted: 0},
	{initialAngle: 0},
	{door: 0},
	{dedraSticker: 0},
	{inspectDistance: 0},
	{locaID: 0},
	{hasMobilLocaVariant: 0},
	{mobileLocaID: 0},
	{DestoyIfMobile: 0},
	{inspectable: 0},
	{glassShape: 0},
	{powerUpType: 0},
	{powerUpCollider: 0},
	{targetX: 0},
	{targetZ: 0},
	{distanceToPlayer: 0},
	{randomX: 0},
	{randomY: 0},
	{randomZ: 0},
	{randomAngle: 0},
	{randomizeX: 0},
	{randomizeY: 0},
	{randomizeZ: 0},
	{randomizeAngle: 0},
	{animateScale: 0},
	{randomizationAmount: 0},
	{targetWidth: 0},
	{targetHeight: 0},
	{targetZHeight: 0},
	{animationType: 0},
	{triggerID: 0},
	{triggerSequence: 0},
	{time: 0},
	{scatterShapeTest: 0},
	{transparentShape: 0},
	{achievementType: 0},
	{achievementCollider: 0},
	{skinSelectorFloor: 0},
	{ice: 0},
	{deathZoneTest: 0},
	{startUnixTimeMilliseconds: 0},
	{destroyIfBeforeUnixTimeMilliseconds: 0},
	{destroyBasedOnDate: 0},
	{flag: 0},
	{skinType: 0},
	{targetRate: 0},
	{isPlayer: 0},
	{animation: 0},
	{side: 0},
	{remoteCharacter: 0},
	{isCenter: 0},
	{skinLookupIndex: 0},
	{skinViewModel: 0},
	{sessionId: 0},
	{vx: 0},
	{vy: 0},
	{vz: 0},
	{inState: 0},
	{playerName: 0},
	{moveLookAngleDiff: 0},
	{skin: 0},
	{accessory: 0},
	{RemotePlayer: 0},
	{staticCharacter: 0},
	{NoOnline: 0},
	{IsHub: 0},
	{PrefabHolder: 0},
	{PrefabToSpawn: 0},
	{Prefab: 0},
	{disableRequirement: 0},
	{SlowmoZone: 0},
	{PhotoTuto: 0},
	{EmotesTuto: 0},
	{buttons: 0},
	{i18nText: 0},
	{anchors: 0},
	{timescale3DObject: 0},
	{timescale3Dshape: 0},
	{timescaleSprite: 0},
	{Solid: 0},
	{solid: 0},
	{catchesRay: 0},
	{soundSource: 0},
	{distanceCull3DObject: 0},
	{pressurePlates: 0},
	{pickUps: 0},
	{"3dParticles": 0},
	{skybox: 0},
	{inspectables: 0},
	{static3DObjects: 0},
	{worldHudTarget: 0},
	{doors: 0},
	{semiTransparency: 0},
	{skyplanes: 0},
	{isAimingAt: 0},
	{powerUp: 0},
	{scatterShape: 0},
	{proximityFadeText: 0},
	{hasSkin: 0},
	{distanceAnimationRate: 0},
	{deathZone: 0},
	{angle1: 0},
	{minimum: 0},
	{maximum: 0},
	{fromMin: 0},
	{fromMax: 0},
	{toMin: 0},
	{toMax: 0},
	{x1: 0},
	{y1: 0},
	{z1: 0},
	{x2: 0},
	{y2: 0},
	{z2: 0},
	{maxValue: 0},
	{uid: 0},
	{uid2: 0},
	{a: 0},
	{b: 0},
	{t: 0},
	{decay: 0},
	{delta: 0},
	{value1: 0},
	{value2: 0},
	{tolerance: 0},
	{interval: 0},
	{pixel: 0},
	{meter: 0},
	{colorName: 0},
	{colorValue: 0},
	{UID: 0},
	{path: 0},
	{seconds: 0},
	{chapterName: 0},
	{levelName: 0},
	{bestTime: 0},
	{levelTime: 0},
	{chapter: 0},
	{temp: 0},
	{layName: 0},
	{isWatchingAdd: 0},
	{gameplayStarted: 0},
	{gameplayStartedIntent: 0},
	{waitForFirstInput: 0},
	{rewardType: 0},
	{EnableDevCheats: 0},
	{hoveredButtonUID: 0},
	{OPTIONS: 0},
	{tokens: 0},
	{curToken: 0},
	{text: 0},
	{displayLength: 0},
	{menuWasVisible: 0},
	{dialogID: 0},
	{curLevelIndex: 0},
	{previousHadBestTime: 0},
	{i: 0},
	{counter: 0},
	{audioName: 0},
	{minRate: 0},
	{maxRate: 0},
	{songIsForced: 0},
	{songName: 0},
	{curSongIndex: 0},
	{curSongTableIndex: 0},
	{failAmount: 0},
	{STEP_SIZE: 0},
	{MAX_RECORD_LENGTH: 0},
	{lastStepTime: 0},
	{skyboxSize: 0},
	{density: 0},
	{currentScroll: 0},
	{waveScrollSpeed: 0},
	{curInspectableUID: 0},
	{doorInteractDistance: 0},
	{direction: 0},
	{targetTimescale: 0},
	{isInSlowMotion: 0},
	{curAimingAtUID: 0},
	{castDistance: 0},
	{objectType: 0},
	{distanceThreshold: 0},
	{preFinish: 0},
	{amount: 0},
	{shouldUnlock: 0},
	{animationPlayed: 0},
	{progress: 0},
	{inputFocus: 0},
	{coyoteTimeAddition: 0},
	{HorizontalAxis: 0},
	{VerticalAxis: 0},
	{unadjustWorkedOnce: 0},
	{unadjustLockFailCount: 0},
	{curStickTouchID: 0},
	{curLookTouchID: 0},
	{curStickTouchAngle: 0},
	{curStickTouchDistance: 0},
	{gyroXmovement: 0},
	{gyroYmovement: 0},
	{aspectRatio: 0},
	{x: 0},
	{y: 0},
	{tap1Time: 0},
	{tap1Duration: 0},
	{hasTapped1: 0},
	{maxTapDelay: 0},
	{maxTapDuration: 0},
	{wishDirX: 0},
	{wishDirY: 0},
	{currentSpeed: 0},
	{addSpeed: 0},
	{drop: 0},
	{newspeed: 0},
	{frictionMul: 0},
	{maxGlideTime: 0},
	{glideModifier: 0},
	{moonGravity: 0},
	{wallRunWallClimbCancelWindow: 0},
	{isWallClimb: 0},
	{angleTest: 0},
	{unrotatedX: 0},
	{unrotatedY: 0},
	{closestSide: 0},
	{shapeWidth: 0},
	{shapeHeight: 0},
	{speed: 0},
	{distanceToCheck: 0},
	{checkAngle: 0},
	{extraZStep: 0},
	{jumpStrengthMultiplier: 0},
	{jumpAngle: 0},
	{longWallJump: 0},
	{jumpWasUsed: 0},
	{targetFOV: 0},
	{size: 0},
	{BOUNCE_GROUND_STRENGTH: 0},
	{lastX: 0},
	{lastY: 0},
	{id2: 0},
	{saveLoaded: 0},
	{language: 0},
	{region: 0},
	{length: 0},
	{color: 0},
	{limitType: 0},
	{targetQuality: 0},
	{touchedFloor: 0},
	{surfTime: 0},
	{fallStartY: 0},
	{fallsSameLevel: 0},
	{previousLevel: 0},
	{achievementID: 0},
	{camWallrunTilt: 0},
	{signedAngleDiff: 0},
	{lerpedWallNormalAngle: 0},
	{upX: 0},
	{upY: 0},
	{upZ: 0},
	{camWorldX: 0},
	{camWorldY: 0},
	{MovementX: 0},
	{MovementY: 0},
	{rotX: 0},
	{rotY: 0},
	{rotation: 0},
	{duration: 0},
	{xShake: 0},
	{yShake: 0},
	{playerSpeed: 0},
	{shakeLength: 0},
	{shakeStrength: 0},
	{timerTime: 0},
	{levelState: 0},
	{template: 0},
	{to: 0},
	{collectedStars: 0},
	{z: 0},
	{layerNumber: 0},
	{lifetime: 0},
	{sprayDistance: 0},
	{dontOpenPauseMenu: 0},
	{isDebugUIEnabled: 0},
	{online: 0},
	{resetting: 0},
	{disconnecting: 0},
	{connecting: 0},
	{waitingToConnect: 0},
	{disableOnline: 0},
	{firstInit: 0},
	{roomName: 0},
	{endpoint: 0},
	{queuedEmote: 0},
	{emoteType: 0},
	{sessionID: 0},
	{AngPackMax: 0},
	{enum: 0},
	{UPDATE_RATE: 0},
	{stateJSON: 0},
	{WALL_RUN_OFFSET: 0},
	{name: 0},
	{remotePlayerUID: 0},
	{powerUpDuration: 0},
	{moonPhysicsTimer: 0},
	{momentumFloorTimer: 0},
	{airDashTimer: 0},
	{lastCollectedPowerUp: 0},
	{isCheated: 0},
	{layerName: 0},
	{SPACING: 0},
	{currentPlayerSkinIndex: 0},
	{rotateSpeed: 0},
	{inspectState: 0},
	{camPlayerDist: 0},
	{skinConcatName: 0},
	{curFocalDistance: 0},
	{minFocusDistane: 0},
	{maxFocalDistance: 0},
	{previousGraphicsQuality: 0},
	{virtualX: 0},
	{virtualY: 0},
	{dist: 0},
	{SelectedIconUID: 0},
	{BaseMomentum: 0},
	{isHunter: 0},
	{currentHunterSessionID: 0},
	{distance3DtoHunter: 0},
	{LOADING_TEXT: 0}
];

self.InstanceType = {
	Inputs: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	camera: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	save: class extends self.IJSONInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	globalManager: class extends self.ISpriteInstance {},
	levelData: class extends self.IJSONInstance {},
	playlist: class extends self.IJSONInstance {},
	tempGhost: class extends self.IJSONInstance {},
	i18n: class extends self.IInstance {},
	PokiSDK: class extends self.IInstance {},
	ClippingMask: class extends self.IWorldInstance {},
	achievementData: class extends self.IJSONInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	LimitFPS: class extends self.IInstance {},
	Colyseus: class extends self.IInstance {},
	playerDataJSON: class extends self.IJSONInstance {},
	GlobalRuntime: class extends self.IInstance {},
	doorCollider: class extends self.I3DShapeInstance {},
	names: class extends self.IJSONInstance {},
	rayCastData: class extends self.ISpriteInstance {},
	powerUpState: class extends self.IJSONInstance {},
	skinDataJSON: class extends self.IJSONInstance {},
	Date: class extends self.IInstance {},
	skybox_cloudy: class extends self.I3DShapeInstance {},
	cloudPlane: class extends self.ITiledBackgroundInstance {},
	skybox_gradient: class extends self.I3DShapeInstance {},
	skybox_deepBlue: class extends self.I3DShapeInstance {},
	skybox_greySky: class extends self.I3DShapeInstance {},
	skybox_frosty: class extends self.I3DShapeInstance {},
	deformPlane: class extends self.ITiledBackgroundInstance {},
	_3DObjectPowerUp: class extends self.IWorldInstance {},
	PowerUpWorldText: class extends self.ITextInstance {},
	edgesTexture: class extends self.IWorldInstance {},
	blackFillTexture: class extends self.ISpriteInstance {},
	concreteTexture: class extends self.ISpriteInstance {},
	darkTarTexture: class extends self.ISpriteInstance {},
	gridTexture: class extends self.ITiledBackgroundInstance {},
	dirtyEdgesTexture: class extends self.ISpriteInstance {},
	speedTexture: class extends self.ITiledBackgroundInstance {},
	powerBoxSideTexture: class extends self.ISpriteInstance {},
	powerBoxTopTexture: class extends self.ISpriteInstance {},
	tarpTexture: class extends self.ISpriteInstance {},
	TilesTexture: class extends self.ITiledBackgroundInstance {},
	stripesTexture: class extends self.ITiledBackgroundInstance {},
	crossPatternTexture: class extends self.ITiledBackgroundInstance {},
	plankTexture: class extends self.ISpriteInstance {},
	cardBoardBox: class extends self.ISpriteInstance {},
	whiteRectangleTexture: class extends self.ISpriteInstance {},
	ventShaftTileTexture: class extends self.ITiledBackgroundInstance {},
	vent: class extends self.ISpriteInstance {},
	ventShaftTileSquashedTexture: class extends self.ITiledBackgroundInstance {},
	TilesTextureDark: class extends self.ITiledBackgroundInstance {},
	verticalPanelTexture: class extends self.ITiledBackgroundInstance {},
	containerSides: class extends self.ISpriteInstance {},
	containerShortSide: class extends self.ISpriteInstance {},
	zCorpTexture: class extends self.ISpriteInstance {},
	attentionTexture: class extends self.ISpriteInstance {},
	concreteTextureUnderside: class extends self.ISpriteInstance {},
	arrowTexture: class extends self.ISpriteInstance {},
	zzCorpLogoTexture: class extends self.ISpriteInstance {},
	brightCornersTexture: class extends self.ISpriteInstance {},
	pressurePlateTopTexture: class extends self.ISpriteInstance {},
	grafittiTestTexture: class extends self.ISpriteInstance {},
	brickTexture: class extends self.ITiledBackgroundInstance {},
	yellowWhiteTexture: class extends self.ISpriteInstance {},
	whiteTexture: class extends self.ISpriteInstance {},
	ArrowDown: class extends self.ISpriteInstance {},
	woodPlanksTexture: class extends self.ITiledBackgroundInstance {},
	sandstoneBricksTexture: class extends self.ITiledBackgroundInstance {},
	sandStoneTexture: class extends self.ISpriteInstance {},
	graffitiPiece: class extends self.ISpriteInstance {},
	glassTexture: class extends self.ISpriteInstance {},
	doorTexture: class extends self.ISpriteInstance {},
	solarPanelTexture: class extends self.ITiledBackgroundInstance {},
	doorTextureMirrored: class extends self.ISpriteInstance {},
	holdOnHL2: class extends self.ISpriteInstance {},
	ArrowUp: class extends self.ISpriteInstance {},
	iceTexture: class extends self.ISpriteInstance {},
	snowTopTexture: class extends self.ISpriteInstance {},
	snowTiles9p: class extends self.IWorldInstance {},
	Text_performance: class extends self.ITextInstance {},
	sliderBar: class extends self.IWorldInstance {},
	Text_slider: class extends self.ITextInstance {},
	Text_inputs: class extends self.ITextInstance {},
	Text_button: class extends self.ITextInstance {},
	basicButton: class extends self.IWorldInstance {},
	whiteFillTexture: class extends self.ISpriteInstance {},
	anchor: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	Text_bestTime: class extends self.ITextInstance {},
	Text_Timer: class extends self.ITextInstance {},
	crosshair: class extends self.ISpriteInstance {},
	starCompletedFill: class extends self.ISpriteInstance {},
	loadingBar: class extends self.ITiledBackgroundInstance {},
	achievementBG: class extends self.ISpriteInstance {},
	Text_achievement: class extends self.ITextInstance {},
	dialogBg: class extends self.IWorldInstance {},
	levelSelectButton: class extends self.IWorldInstance {},
	levelSelectStarFill: class extends self.ISpriteInstance {},
	levelSelectStarUI: class extends self.ISpriteInstance {},
	Text_dialogHeader: class extends self.ITextInstance {},
	Text_levelName: class extends self.ITextInstance {},
	Text_levelSelectBestTime: class extends self.ITextInstance {},
	sliderHandle: class extends self.IWorldInstance {},
	bbox: class extends self.ISpriteInstance {},
	scrollView: class extends self.ISpriteInstance {},
	Text_DevNames: class extends self.ITextInstance {},
	Text_curLevelTimes: class extends self.ITextInstance {},
	Text_curLevelDataHeader: class extends self.ITextInstance {},
	logo: class extends self.ISpriteInstance {},
	loadingBarBg: class extends self.ITiledBackgroundInstance {},
	achievementSymbol: class extends self.ISpriteInstance {},
	touchStickInner: class extends self.ISpriteInstance {},
	touchStickOuterCircle: class extends self.ISpriteInstance {},
	icons: class extends self.ISpriteInstance {},
	achievementUnlock: class extends self.IWorldInstance {},
	Text_achievementUnlock: class extends self.ITextInstance {},
	Text_achievementUnlockCounter: class extends self.ITextInstance {},
	Text_CreditText: class extends self.ITextInstance {},
	screenMessageBG: class extends self.ISpriteInstance {},
	text_screenMessage: class extends self.ITextInstance {},
	levelSelectSecretBG: class extends self.ISpriteInstance {},
	Text_rewardedDialogText: class extends self.ITextInstance {},
	chapterProgress: class extends self.IWorldInstance {},
	chapterProgressHeaderBG: class extends self.IWorldInstance {},
	Text_ChapterProgressHeader: class extends self.ITextInstance {},
	chapterProgressMarker: class extends self.ISpriteInstance {},
	Text_ChapterName: class extends self.ITextInstance {},
	chapterProgressBar: class extends self.ITiledBackgroundInstance {},
	chapterProgressBarBG: class extends self.ITiledBackgroundInstance {},
	cursor: class extends self.ISpriteInstance {},
	worldHudMarker: class extends self.ISpriteInstance {},
	Text_inspectable: class extends self.ITextInstance {},
	messageBg: class extends self.IWorldInstance {},
	lockPointerText: class extends self.ITextInstance {},
	worldTargetDistanceText: class extends self.ITextInstance {},
	loadingText: class extends self.ITextInstance {},
	achievementProgressBar: class extends self.ITiledBackgroundInstance {},
	achievementProgressBarBG: class extends self.ITiledBackgroundInstance {},
	Text_achievementUnlockHeader: class extends self.ITextInstance {},
	Text_achievementHeader: class extends self.ITextInstance {},
	emoteWheel: class extends self.ISpriteInstance {},
	emoteIcon: class extends self.ISpriteInstance {},
	emoteWheelArrow: class extends self.ISpriteInstance {},
	emote: class extends self.ISpriteInstance {},
	loadingRandomText: class extends self.ITextInstance {},
	playerProfileBG: class extends self.IWorldInstance {},
	Text_playerName: class extends self.ITextInstance {},
	musicPlayer: class extends self.IWorldInstance {},
	Text_SongArtistName: class extends self.ITextInstance {},
	curLevelDataBG: class extends self.IWorldInstance {},
	coverBGMask: class extends self.ISpriteInstance {},
	emptyEmoteIcon: class extends self.IWorldInstance {},
	hasMultiplayerIcon: class extends self.ISpriteInstance {},
	playerProfilePicture: class extends self.ISpriteInstance {},
	uiCorner: class extends self.ISpriteInstance {},
	staticLocaText: class extends self.ITextInstance {},
	TagPopup: class extends self.ITextInstance {},
	world_text: class extends self.ITextInstance {},
	Text_leadsToHeader: class extends self.ITextInstance {},
	leadsToBG: class extends self.IWorldInstance {},
	Text_LeadsToInfo: class extends self.ITextInstance {},
	Text_photoMode: class extends self.ITextInstance {},
	cameraInfoBg: class extends self.IWorldInstance {},
	focalBar: class extends self.ITiledBackgroundInstance {},
	cameraFocusIcons: class extends self.ISpriteInstance {},
	focusingSliderHead: class extends self.ISpriteInstance {},
	photoModeRect: class extends self.IWorldInstance {},
	cameraShutterMask: class extends self.ITiledBackgroundInstance {},
	levelEndParticles: class extends self.IParticlesInstance {},
	powerUpIcon: class extends self.ISpriteInstance {},
	powerUpBG: class extends self.ISpriteInstance {},
	Text_remotePlayerName: class extends self.ITextInstance {},
	remotePlayerHudParent: class extends self.ISpriteInstance {},
	powerUpProgress: class extends self.ISpriteInstance {},
	skinStateIcon: class extends self.ISpriteInstance {},
	skinviewUI: class extends self.ISpriteInstance {},
	skinDescription: class extends self.ITiledBackgroundInstance {},
	Text_UnlockHardTrials: class extends self.ITextInstance {},
	Text_skinDescription: class extends self.ITextInstance {},
	Text_skinName: class extends self.ITextInstance {},
	Text_skinUnlocked: class extends self.ITextInstance {},
	Text_coinChange: class extends self.ITextInstance {},
	Text_playerData: class extends self.ITextInstance {},
	text_coins: class extends self.ITextInstance {},
	Text_changeName: class extends self.ITextInstance {},
	uiGrouper: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	playerShadow: class extends self.ISpriteInstance {},
	GhostShape: class extends self.I3DShapeInstance {},
	cctvCamera: class extends self.IWorldInstance {},
	Cone: class extends self.IWorldInstance {},
	Pipe: class extends self.IWorldInstance {},
	cable: class extends self.IWorldInstance {},
	edgeTarp: class extends self.IWorldInstance {},
	cornerTarp: class extends self.IWorldInstance {},
	pole: class extends self.IWorldInstance {},
	snowman: class extends self.IWorldInstance {},
	endZone: class extends self.I3DShapeInstance {},
	startZone: class extends self.I3DShapeInstance {},
	solidCollisionShape: class extends self.I3DShapeInstance {},
	pressurePlateHelper: class extends self.ISpriteInstance {},
	pressurePlate1: class extends self.I3DShapeInstance {},
	pickUpCrystal: class extends self.I3DShapeInstance {},
	speedFloor: class extends self.I3DShapeInstance {},
	pickUpAsset: class extends self.IWorldInstance {},
	test3dParticle: class extends self.I3DShapeInstance {},
	stripes: class extends self.I3DShapeInstance {},
	decal: class extends self.I3DShapeInstance {},
	grafittiTestDecal: class extends self.I3DShapeInstance {},
	VerticalFootstep: class extends self.I3DShapeInstance {},
	decal2: class extends self.I3DShapeInstance {},
	grafittiTestDecal2: class extends self.I3DShapeInstance {},
	decal3: class extends self.I3DShapeInstance {},
	concreteShape: class extends self.I3DShapeInstance {},
	tarpBox: class extends self.I3DShapeInstance {},
	metalGround: class extends self.I3DShapeInstance {},
	railing: class extends self.IWorldInstance {},
	powerBox: class extends self.I3DShapeInstance {},
	blackShape: class extends self.I3DShapeInstance {},
	TiledShape: class extends self.I3DShapeInstance {},
	plank: class extends self.I3DShapeInstance {},
	box: class extends self.I3DShapeInstance {},
	ventPipe: class extends self.I3DShapeInstance {},
	woodPlanksShape: class extends self.I3DShapeInstance {},
	verticalPanels: class extends self.I3DShapeInstance {},
	TiledShape2: class extends self.I3DShapeInstance {},
	pickUpTest: class extends self.I3DShapeInstance {},
	whiteYellowWall: class extends self.I3DShapeInstance {},
	simpleWhiteWall: class extends self.I3DShapeInstance {},
	brokenConcretePillar: class extends self.IWorldInstance {},
	manhole: class extends self.ISpriteInstance {},
	mural: class extends self.ISpriteInstance {},
	mural2: class extends self.ISpriteInstance {},
	neverRainSticker: class extends self.ISpriteInstance {},
	wireMesh: class extends self.IWorldInstance {},
	footstepDecal: class extends self.ISpriteInstance {},
	footstepDecal2: class extends self.ISpriteInstance {},
	footstepDecal3: class extends self.ISpriteInstance {},
	TiledShape3: class extends self.I3DShapeInstance {},
	sandStoneBrickShape: class extends self.I3DShapeInstance {},
	sandStoneShape: class extends self.I3DShapeInstance {},
	door: class extends self.I3DShapeInstance {},
	dedraSticker: class extends self.ISpriteInstance {},
	inspectable: class extends self.I3DShapeInstance {},
	glassShape: class extends self.I3DShapeInstance {},
	powerUpCollider: class extends self.I3DShapeInstance {},
	scatterShapeTest: class extends self.I3DShapeInstance {},
	transparentShape: class extends self.I3DShapeInstance {},
	achievementCollider: class extends self.I3DShapeInstance {},
	skinSelectorFloor: class extends self.I3DShapeInstance {},
	ice: class extends self.I3DShapeInstance {},
	deathZoneTest: class extends self.I3DShapeInstance {},
	destroyBasedOnDate: class extends self.ISpriteInstance {},
	flag: class extends self.ISpriteInstance {},
	remoteCharacter: class extends self.IWorldInstance {},
	skinViewModel: class extends self.IWorldInstance {},
	RemotePlayer: class extends self.I3DShapeInstance {},
	staticCharacter: class extends self.IWorldInstance {},
	NoOnline: class extends self.IWorldInstance {},
	IsHub: class extends self.IWorldInstance {},
	PrefabHolder: class extends self.ISpriteInstance {},
	Prefab: class extends self.ISpriteInstance {},
	SlowmoZone: class extends self.I3DShapeInstance {},
	PhotoTuto: class extends self.ISpriteInstance {},
	EmotesTuto: class extends self.ISpriteInstance {},
	buttons: class extends self.IWorldInstance {},
	i18nText: class extends self.ITextInstance {},
	anchors: class extends self.ISpriteInstance {},
	timescale3DObject: class extends self.IWorldInstance {},
	timescale3Dshape: class extends self.I3DShapeInstance {},
	timescaleSprite: class extends self.ISpriteInstance {},
	solid: class extends self.I3DShapeInstance {},
	catchesRay: class extends self.I3DShapeInstance {},
	soundSource: class extends self.I3DShapeInstance {},
	distanceCull3DObject: class extends self.IWorldInstance {},
	pressurePlates: class extends self.I3DShapeInstance {},
	pickUps: class extends self.I3DShapeInstance {},
	_3dParticles: class extends self.I3DShapeInstance {},
	skybox: class extends self.I3DShapeInstance {},
	inspectables: class extends self.I3DShapeInstance {},
	static3DObjects: class extends self.IWorldInstance {},
	worldHudTarget: class extends self.I3DShapeInstance {},
	doors: class extends self.I3DShapeInstance {},
	semiTransparency: class extends self.I3DShapeInstance {},
	skyplanes: class extends self.ITiledBackgroundInstance {},
	isAimingAt: class extends self.I3DShapeInstance {},
	powerUp: class extends self.I3DShapeInstance {},
	scatterShape: class extends self.I3DShapeInstance {},
	proximityFadeText: class extends self.ITextInstance {},
	hasSkin: class extends self.IWorldInstance {},
	distanceAnimationRate: class extends self.IWorldInstance {},
	deathZone: class extends self.I3DShapeInstance {}
}